services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api
    image: gestion-ventas-frontend:latest
    container_name: gestion_ventas_frontend_app
    ports:
      - "127.0.0.1:3091:80"
    networks:
      - rioverde_ventas_net
    restart: unless-stopped

networks:
  rioverde_ventas_net:
    external: true
